

//[[define image infomation

RES_ADD_IMG(IMG_PEEKMAIL_MAINMENU_ICON,"\\MMI_RES_##\\IMAG\\peek_mail_icon.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_STAR_ICON,"\\MMI_RES_##\\IMAG\\starred.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_UNREAD_ICON,"\\MMI_RES_##\\IMAG\\mail_unread.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_READ_ICON,"\\MMI_RES_##\\IMAG\\mail_read.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_ACTIVE_ICON,"\\MMI_RES_##\\IMAG\\active.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_PRIMARY_ICON,"\\MMI_RES_##\\IMAG\\primary.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_DEACTIVE_ICON,"\\MMI_RES_##\\IMAG\\de-active.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMG_PEEKMAIL_PEEK_LOGO,"\\MMI_RES_##\\IMAG\\peek_logo.jpg",IMG_CMP_JPG_STD,0)

//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation

RES_ADD_STRING(TXT_PEEKMAIL_MENU_TITLE, "Pmail")
RES_ADD_STRING(TXT_PEEKMAIL_TITLE, "Peek Mail")
RES_ADD_STRING(TXT_PEEKMAIL_MENU, "Menu")
RES_ADD_STRING(TXT_PEEKMAIL_OK, "OK")
RES_ADD_STRING(TXT_PEEKMAIL_VIEW, "View")
RES_ADD_STRING(TXT_PEEKMAIL_BACK, "Back")

RES_ADD_STRING(TXT_PEEKMAIL_INBOX_TITLE, "Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_SAVED_TITLE, "Saved")
RES_ADD_STRING(TXT_PEEKMAIL_DRAFTS_TITLE, "Drafts")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_TITLE, "Sent")
RES_ADD_STRING(TXT_PEEKMAIL_TRASH_TITLE, "Trash")
RES_ADD_STRING(TXT_PEEKMAIL_ALL_TITLE, "All")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_TITLE, "New")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_TITLE, "Pmail Manager")


RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_OPEN_MESSAGE_ITEM, "Open Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_COMPOSE_ITEM, "Compose")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_REPLY_ITEM, "Reply")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_REPLY_ALL_ITEM, "Reply All")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_FORWARD_ITEM, "Forward")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_MARK_READ_UNREAD_ITEM, "Mark read/unread")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SAVE_MESSAGE_ITEM, "Save Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DELETE_MESSAGE_ITEM, "Delete Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DELETE_ALL_ITEM, "Delete All")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SENT_FOLDER_ITEM, "Sent Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DRAFTS_FOLDER_ITEM, "Drafts Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SAVED_FOLDER_ITEM, "Saved Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_TRASH_FOLDER_ITEM, "Trash Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SEARCH_THIS_FOLDER_ITEM, "Search This Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_CONTACTS_ITEM, "Contacts")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_PEEK_MAIL_MANAGER_ITEM, "Peek Mail Manager")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_EXIT_ITEM, "Exit")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_MENU_INBOX_FOLDER_ITEM, "Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_MENU_MOVE_TO_INBOX_FOLDER_ITEM, "Move to Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_SEND_MESSAGE_ITEM, "Send")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_SAVE_AS_DRAFT_ITEM, "Save as draft")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_ADD_CC_ITEM, "Add CC")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_ADD_BCC_ITEM, "Add BCC")

RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_PROMPT_WANNA_SAVE, "Save as Draft?")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_PROMPT_TEXT_SAVED_SENT, "Saved as Sent!")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_PROMPT_TEXT_SAVED_DRAFT, "Saved as Draft!")

RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_MAIN_MENU_EMAIL_ACCOUNTS, "Email Accounts")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_MAIN_MENU_EMAIL_STORAGE, "Email Storage")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_MAIN_MENU_ABOUT,		"About")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_MAIN_MENU_RESET_PMAIL,  "Reset Pmail")

RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_MENU_EDIT_ACCOUNTS,  "Edit Account")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_MENU_NEW_ACCOUNTS,	"New Account")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_MENU_DEL_ACCOUNTS,  "Delete Account")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_MENU_SET_AS_PRIMARY,  "Set as primary")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_MENU_DOWNLOAD_CONTACTS,  "Download Contacts")

RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_TITLE, "Accounts")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ACCOUNT_EDITOR_TITLE, "Account")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_STORAGE_TITLE, "Storage")

RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_STORAGE_TYPE_PHONE, "Phone(recommended)")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_STORAGE_TYPE_SDCARD, "SD Card")

RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_ABOUT_PEEKMAIL, "About PeekMail")
RES_ADD_STRING(TXT_PEEKMAIL_MANAGER_RESET_SUCCESSFULLY, "Reset Accounts Successfully!")
	
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_NEW_CONTACT, "New Contact")
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_DOWNLOAD_CONTACTS, "Download Contacts")
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_TITLE, "Contact")
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_DOWNLOAD_SUCCESSFULLY, "Contact Download Successfully!")
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_EDIT_SAVE_DETAILS, "Save Details")
RES_ADD_STRING(TXT_PEEKMAIL_CONTACT_EDIT_SAVE_CONTACT_SUCCESSFULLY, "Save Contact Successfully!")

RES_ADD_STRING(TXT_PEEKMAIL_DELETE_ALL_SUCCESSFULLY, "Delete All Successfully!")
RES_ADD_STRING(TXT_PEEKMAIL_SEARCH_TITLE, "Search")

RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_FROM_1,"Jennifer Conlan Darlinton")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_FROM_2,"Amazon.com Email")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_FROM_3,"Peek Inc. Custom Service")

RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_TIME_1,"11:30 PM")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_TIME_2,"05:26 AM")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_TIME_3,"Yesterday")

RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_SUBJ_1,"Notification about graduation in Spring 2011")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_SUBJ_2,"Amazon.com Gold Box Deal of the Day")
RES_ADD_STRING(TXT_PEEKMAIL_EXAMPLE_SUBJ_3,"Great Opportunities")









//]]define string infomation





//[[define data infomation

//]]define data infomation
