

//[[define image infomation

RES_ADD_IMG(IMG_PEEKMAIL_MAINMENU_ICON,"\\MMI_RES_##\\IMAG\\peek_mail_icon.jpg",IMG_CMP_JPG_STD,0)

//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation

RES_ADD_STRING(TXT_PEEKMAIL_MENU_TITLE, "Pmail")
RES_ADD_STRING(TXT_PEEKMAIL_TITLE, "Peek Mail")
RES_ADD_STRING(TXT_PEEKMAIL_MENU, "Menu")
RES_ADD_STRING(TXT_PEEKMAIL_VIEW, "View")
RES_ADD_STRING(TXT_PEEKMAIL_BACK, "Back")

RES_ADD_STRING(TXT_PEEKMAIL_INBOX_TITLE, "Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_SAVED_TITLE, "Saved")
RES_ADD_STRING(TXT_PEEKMAIL_DRAFTS_TITLE, "Drafts")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_TITLE, "Sent")
RES_ADD_STRING(TXT_PEEKMAIL_TRASH_TITLE, "Trash")
RES_ADD_STRING(TXT_PEEKMAIL_ALL_TITLE, "All")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_TITLE, "New")


RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_OPEN_MESSAGE_ITEM, "Open Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_COMPOSE_ITEM, "Compose")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_REPLY_ITEM, "Reply")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_REPLY_ALL_ITEM, "Reply All")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_FORWARD_ITEM, "Forward")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_MARK_READ_UNREAD_ITEM, "Mark read/unread")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SAVE_MESSAGE_ITEM, "Save Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DELETE_MESSAGE_ITEM, "Delete Message")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DELETE_ALL_ITEM, "Delete All")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SENT_FOLDER_ITEM, "Sent Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_DRAFTS_FOLDER_ITEM, "Drafts Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SAVED_FOLDER_ITEM, "Saved Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_TRASH_FOLDER_ITEM, "Trash Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_SEARCH_THIS_FOLDER_ITEM, "Search This Folder")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_CONTACTS_ITEM, "Contacts")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_PEEK_MAIL_MANAGER_ITEM, "Peek Mail Manager")
RES_ADD_STRING(TXT_PEEKMAIL_INBOX_MENU_EXIT_ITEM, "Exit")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_MENU_INBOX_FOLDER_ITEM, "Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_SENT_MENU_MOVE_TO_INBOX_FOLDER_ITEM, "Move to Inbox")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_SEND_MESSAGE_ITEM, "Send")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_SAVE_AS_DRAFT_ITEM, "Save as draft")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_ADD_CC_ITEM, "Add CC")
RES_ADD_STRING(TXT_PEEKMAIL_COMPOSER_MENU_ADD_BCC_ITEM, "Add BCC")


//]]define string infomation





//[[define data infomation

//]]define data infomation
