
// Window ID
typedef enum
{
	MMIPEEKMAIL_WIN_ID_START = (MMI_MODULE_PEEKMAIL << 16),
		
	MMI_PEEK_MAIL_WIN_ID,
	MMI_PEEK_MAIL_INBOX_WIN_ID,
	MMI_PEEK_MAIL_INBOX_MENU_WIN_ID,
	MMI_PEEK_MAIL_SENT_WIN_ID,
	MMI_PEEK_MAIL_SENT_MENU_WIN_ID,
	MMI_PEEK_MAIL_SAVED_WIN_ID,
	MMI_PEEK_MAIL_SAVED_MENU_WIN_ID,
	MMI_PEEK_MAIL_COMPOSER_WIN_ID,
	MMI_PEEK_MAIL_COMPOSER_MENU_WIN_ID,
	MMI_PEEK_MAIL_DRAFT_WIN_ID,
	MMI_PEEK_MAIL_DRAFT_MENU_WIN_ID,
	MMI_PEEK_MAIL_TRASH_WIN_ID,
	MMI_PEEK_MAIL_TRASH_MENU_WIN_ID,
	MMI_PEEK_MAIL_VIEW_WIN_ID,
	

	MMIPEEKMAIL_MAX_WIN_ID
}MMIPEEKMAIL_WINDOW_ID_E;


// Control ID
typedef enum
{
	MMIPEEKMAIL_CTRL_ID_ID_START = MMIPEEKMAIL_MAX_WIN_ID,
		
	MMI_PEEK_MAIL_INBOX_CTRL_ID,
	MMI_PEEK_MAIL_INBOX_MENU_CTRL_ID,
	MMI_PEEK_MAIL_SENT_CTRL_ID,
	MMI_PEEK_MAIL_SENT_MENU_CTRL_ID,
	MMI_PEEK_MAIL_SAVED_CTRL_ID,
	MMI_PEEK_MAIL_SAVED_MENU_CTRL_ID,
	MMI_PEEK_MAIL_DRAFT_CTRL_ID,
	MMI_PEEK_MAIL_DRAFT_MENU_CTRL_ID,
	MMI_PEEK_MAIL_TRASH_CTRL_ID,
	MMI_PEEK_MAIL_TRASH_MENU_CTRL_ID,

	MMI_PEEK_MAIL_VIEW_RICHTEXT_CTRL_ID,


	MMI_PEEK_MAIL_COMPOSER_MENU_CTRL_ID,
	
	MMI_PEEK_MAIL_COMPOSER_FORM_CTRL_ID,
		MMI_PEEK_MAIL_COMPOSER_FROM_FORM_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_LABEL_FROM_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_EDITBOX_FROM_CTRL_ID,
		MMI_PEEK_MAIL_COMPOSER_TO_FORM_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_LABEL_TO_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_EDITBOX_TO_CTRL_ID,
		MMI_PEEK_MAIL_COMPOSER_SUBJECT_FORM_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_LABEL_SUBJECT_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_EDITBOX_SUBJECT_CTRL_ID,
		MMI_PEEK_MAIL_COMPOSER_TEXT_FORM_CTRL_ID,
			MMI_PEEK_MAIL_COMPOSER_EDITBOX_TEXT_CTRL_ID,

	MMIPEEKMAIL_MAX_CTRL_ID
}MMIPEEKMAIL_CONTROL_ID_E;

